# Kryptografi 1

In [1]:
import numpy as np

## Oppgave 1

232 + 32 * 77 - 18^2 mod 8

In [2]:
(232 + 32 * 77 - 18**2) % 8

4

## Oppgave 2

### a.
Skriv ut multiplikasjonstabellen i Z12 uten å ha med 0 mod 12


In [3]:
table_size = 12
table = np.zeros((table_size, table_size), dtype=int)

# Fill tables with values
for x in range(table_size):
    for y in range(table_size):
        table[x][y] = ((x + 1) * (y + 1))

mod_table = np.mod(table, 12)
mod_table

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0],
       [ 2,  4,  6,  8, 10,  0,  2,  4,  6,  8, 10,  0],
       [ 3,  6,  9,  0,  3,  6,  9,  0,  3,  6,  9,  0],
       [ 4,  8,  0,  4,  8,  0,  4,  8,  0,  4,  8,  0],
       [ 5, 10,  3,  8,  1,  6, 11,  4,  9,  2,  7,  0],
       [ 6,  0,  6,  0,  6,  0,  6,  0,  6,  0,  6,  0],
       [ 7,  2,  9,  4, 11,  6,  1,  8,  3, 10,  5,  0],
       [ 8,  4,  0,  8,  4,  0,  8,  4,  0,  8,  4,  0],
       [ 9,  6,  3,  0,  9,  6,  3,  0,  9,  6,  3,  0],
       [10,  8,  6,  4,  2,  0, 10,  8,  6,  4,  2,  0],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

### b.

Hvilket tall har multiplikativ invers mod 12?

In [4]:
for x in range(table_size):
    for y in range(table_size):
        if mod_table[x][y] == 1:
            print(x + 1)

1
5
7
11


### c.

Forklar hvorfor en ikke kan ha 0 og 1 i samme rad eller kolonne i tabellen?

#### Svar:
0 og 1 kan ikke forekomme i samme rad eller kolonne fordi 0 og 1 er ekslusive mot hverandre  
For å få 0, kan ikke tallet være relativt primisk med N  
For å få 1, må tallet være relativt primisk med N  

## Oppgave 3

Finn den inverse matrisen til a = [ [2, 5], [-1, 8] ] over...

### a
Z10

### b
Z9

In [5]:
matrix = np.matrix([[2, 5], [-1, 8]], dtype=int)

if np.around(np.linalg.det(matrix)) % 9 == 1:
    print("Mod 9")
    print(np.linalg.inv(matrix))

if np.around(np.linalg.det(matrix)) % 10 == 1:
    print("Mod 10")
    print(np.linalg.inv(matrix))

Mod 10
[[ 0.38095238 -0.23809524]
 [ 0.04761905  0.0952381 ]]


## Oppgave 4

### a
Hvor mange forskjellige nøkler kan et (enkelt) substitusjonschiffer ha når vi opererer med et alfabet med 29 tegn?

In [6]:
# 29!
np.math.factorial(29)

8841761993739701954543616000000

### b
Et slikt substitusjonschiffer er ikke særlig trygt. Hvilke enkel grep kan Alice og Bob bruke for å gjøre det vanskeligere for Eva å dekode meldingene?

#### Svar:
   * Kan la være å bruke gjentakene språk, som hilsner og samme struktur på meldinger
   * Bruke forskjellige nøkler, slik at hvis en nøkkel blir funnet, kan bare deler av samtalen bli lest
   * Fjerne symboler som bryter opp teksten, som mellomrom, punktum, komma, osv...
   

### c
Hvis vi lager en substitusjonschiffer for blokker med n tegn, hvor mange nøkler finnes da?

#### Svar:
(29^n)!

## Oppgave 5

Du har snappet om følgene  melding:
#### YÆVFB VBVFR ÅVBV
Du vet Alice og Bob bruker et k-skift-chiffer. Finn krypteringsnøkkelen og klarteksten!

In [48]:
alphabet_number = {
    'a' : 0,
    'b' : 1,
    'c' : 2,
    'd' : 3,
    'e' : 4,
    'f' : 5,
    'g' : 6,
    'h' : 7,
    'i' : 8,
    'j' : 9,
    'k' : 10,
    'l' : 11,
    'm' : 12,
    'n' : 13,
    'o' : 14,
    'p' : 15,
    'q' : 16,
    'r' : 17,
    's' : 18,
    't' : 19,
    'u' : 20,
    'v' : 21,
    'w' : 22,
    'x' : 23,
    'y' : 24,
    'z' : 25,
    'æ' : 26,
    'ø' : 27,
    'å' : 28
}

alphabet = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'æ',
    'ø',
    'å'
]

def reformat_index(i):
    if i < 0:
        return 29 + i
    
    return i

input = "yævfbvbvfråvbv"
int_list = []

for char in input:
    int_list.append(alphabet_number[char])
    
for x in range(29):
    print(f'{x}:')
    output = ""
    for i in int_list:
        output += alphabet[reformat_index(i-x)]
    print(output)

0:
yævfbvbvfråvbv
1:
xzueauaueqøuau
2:
wytdåtåtdpætåt
3:
vxscøsøscozsøs
4:
uwrbærærbnyrær
5:
tvqazqzqamxqzq
6:
supåypypålwpyp
7:
rtoøxoxoøkvoxo
8:
qsnæwnwnæjunwn
9:
prmzvmvmzitmvm
10:
oqlyululyhslul
11:
npkxtktkxgrktk
12:
mojwsjsjwfqjsj
13:
lnivririvepiri
14:
kmhuqhqhudohqh
15:
jlgtpgpgtcngpg
16:
ikfsofofsbmfof
17:
hjerneneralene
18:
gidqmdmdqåkdmd
19:
fhcplclcpøjclc
20:
egbokbkboæibkb
21:
dfanjajanzhaja
22:
ceåmiåiåmygåiå
23:
bdølhøhølxføhø
24:
acækgægækweægæ
25:
åbzjfzfzjvdzfz
26:
øayieyeyiucyey
27:
æåxhdxdxhtbxdx
28:
zøwgcwcwgsawcw


K = 17

## Oppgave 6

Definer et blokk-chiffer med blokklengde b, og et alfabete med N tegn, som bruker samme prinsipp som skift-chifret.

Svar:
Ett blokkchifer er en deterministisk algoritme som jobber på en enkel størrelse med bits. Den krypterte meldingen har da en lengde lik blokklengden og har like mange bits i hver blokk

Chifret har (N^b)! nøkler


## Oppgave 7

In [60]:
def create_vigenere_table():
    
    table = np.zeros((29,29), 'U1')
    
    letters = alphabet
    
    for row in range(len(letters)):
        for col in range(len(letters)):
            charToAdd = (col+row) % len(letters)
            table[row][col] = letters[charToAdd]
    return (table, letters)

def encrypt(clearText, key):
    table, letters = create_vigenere_table()
    cipher = ""
    
    for i, letter in enumerate(clearText):
        indexCol = letters.index(letter)
        indexRow = letters.index(key[i % len(key)])
        cipher += table[indexRow][indexCol]
    return cipher

def decrypt(cipher, key):
    table, letters = create_vigenere_table()
    clearText = ""

    for i, letter in enumerate(cipher):
        indexCol = letters.index(letter)
        indexRow = letters.index(key[i % len(key)])
        clearText += letters[(indexCol - indexRow) % len(letters)]
        
    return clearText

a) Krypter teksten “Nå er det snart helg” med nøkkelordet “torsk”.

In [59]:
clearText = "Nå er det snart helg".replace(" ", "").lower()
key = "torsk".lower()

cipher = encrypt(clearText, key)

print("Encrypted cipher: ", cipher)

decrypted = decrypt(cipher, key)
print("Decrypted clearText:", decrypted)

Encrypted cipher:  dnvgnxegckheywvz
Decrypted clearText: nåerdetsnarthelg


b) Dekrypter QZQOBVCAFFKSDC med nøkkelordet “brus”.

In [17]:
cipher = "qzqobvcaffksdc"
key = "brus"

decrypted = decrypt(cipher, key)
print("Decrypted:", decrypted)

Decrypted: pizzaellertaco


c) Hvis m = 5 (se definisjonen), hvor mange nøkler finnes?

Svar: Det finnes 29^5 antall nøkler.

## Oppgave 8

a) Finn K^(−1) over Z_29.

In [61]:
def multiplicative_inverse(matrix):
    array = []
    for x in range(len(matrix)):
        for y in range(len(matrix)):
            if(matrix[x][y] == 1):
                array.append([x+1, y+1])
    return array

def inverse_matrix(A):
    if np.linalg.det(A) != 0:
        return np.linalg.inv(A)*np.linalg.det(A)
    else:
        return None 

def inverse_matrix_over_a(a, z):
    a_det = int(np.linalg.det(a))
    a_det_mod = a_det % len(z)
    z_multipl_inverse = multiplicative_inverse(z)
    det_in_multipl_inverse = False
    
    for x in z_multipl_inverse:
        if a_det_mod in x:
            det_in_multipl_inverse = True
    
    return inverse_matrix(a) if det_in_multipl_inverse else None

In [62]:
K = np.array([[11, 8],[3, 7]])

Z_29 = np.zeros((28, 28))

for x in range(28):
    for y in range(28):
        Z_29[x][y] = ((x+1) * (y+1))

Z_29 = np.mod(Z_29, 29)

K_inv = inverse_matrix_over_a(K, Z_29)
print(K_inv)

[[ 7. -8.]
 [-3. 11.]]


b) Krypter teksten “prim” med K som nøkkel i Hill-chifret.

In [70]:
def vectorize_string(text):
    vector = []
    for letter in text:
        indexLetter = letters.index(letter)
        vector.append(indexLetter)
    vector = np.array(vector)
    return vector

def gcdExtended(a, b):  
    # Base Case  
    if a == 0 :   
        return b, 0, 1
             
    gcd,x1,y1 = gcdExtended(b % a, a)  
     
    # Update x and y using results of recursive  
    # call  
    x = y1 - (b // a) * x1  
    y = x1  
     
    return gcd,x,y 
    
def encrypt_hill(cleartext, k_matrix, key_size=2):
    if(len(cleartext) % 2 == 0):
        cleartext_vector = vectorize_string(cleartext).reshape((-1, key_size))
    else:
        cleartext_vector = vectorize_28string(cleartext + "A").reshape((-1, key_size))
    cipher = ""
    
    e_list = []
    for vector in cleartext_vector:
        encryption = (vector @ k_matrix) % len(letters)
        e_list.append(encryption)
    
    for row in e_list:
        for column in row:
            cipher += letters[column % len(letters)]
            
    return cipher

def decrypt_hill(cipher, K, key_size=2):
    
    Z_29 = np.zeros((28, 28))
    for x in range(28):
        for y in range(28):
            Z_29[x][y] = ((x + 1) * (y + 1))

    Z_29 = np.mod(Z_29, 29)
    
    K_inv = inverse_matrix_over_a(K, Z_29)
    if(K_inv is not None):
        K_det = round(np.linalg.det(K)) % len(letters)
        
        if(len(cipher) % 2 == 0):
            cipher_vector = vectorize_string(cipher).reshape((-1, key_size))
        else:
            cipher_vector = vectorize_string(cipher+"a").reshape((-1, key_size))
            
        x = gcdExtended(K_det, len(letters))[1]
        d_list = []
        
        for vector in cipher_vector:
            decryption = (vector @ (K_inv * x)) % len(letters)
            d_list.append(decryption)

        cleartext = ""
        for row in d_list:
            for column in row:
                cleartext += letters[int(round(column)) % len(letters)]
        return cleartext
    else:
        return ""

In [71]:
letters = alphabet

cleartext_hill= "prim"
cipher_hill_text = encrypt_hill(cleartext_hill, K)
print(cipher_hill_text)


nhid


c) Dekrypter meldingen TOYYSN

In [72]:
cipher = "toyysn"
decrypted = decrypt_hill(cipher, K)
print(decrypted)

fredag


d) For en annen nøkkel med m = 2, så er meldingen EASY kryptert til IØÅY. Finn nøkkelen ut fra bare kjennskap til denne ene meldingen og
dens kryptering.

In [73]:
clearText_string = "easy"
encrypted_string = "iøåy"

# Brute force metode
found_key = False
brute_key = np.array([])
for a in range(21):
    if found_key: break
    for b in range(21):
        if found_key: break
        for c in range(21):
            if found_key: break
            for d in range(21):
                testKey = np.array([[a, b], [c, d]])
                if(decrypt_hill(encrypted_string, testKey) == clearText_string):
                    print("Brute force result:")
                    print(testKey)
                    found_key = True
                    brute_key = testKey
                    break

Brute force result:
[[ 2 14]
 [19  5]]


Svar: